[tool.poetry]
name = "railway-route-generator"
version = "3.0.0"
description = ""
repository="https://github.com/simulate-digital-rail/railway-route-generator"
authors = ["Arne Boockmeyer <arne.boockmeyer@hpi.de>"]
readme = "README.md"
packages = [{include = "railwayroutegenerator"}]

[tool.poetry.dependencies]
python = "^3.10"
yaramo = {git = "https://github.com/simulate-digital-rail/yaramo.git"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
planpro-importer = {git = "https://github.com/jeriox/planpro-python-model", rev = "yaramo"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
